name: CI

on:
  push:
    branches:
      - "main"

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Node
      uses: actions/setup-node@v2

    - name: Install Packages
      run: yarn

    - name: Run lint
      run: yarn check-lint

    - name: Run tests
      run: yarn test